dataloader_type: metric_data
preserve_aspect_ratio: 0
box_extend: 0.1,0.3,0.1,0.1
data:
  # In metric learning, num_features is used to initialize the last layer.
  num_features: 512
  num_classes: 100
  mode: [train, valid]
  train: ../tests/data/metric_data/train.txt
  valid: ../tests/data/metric_data/valid.txt
  test: null
  data_prefix: ../tests/
  sampler:
    batch_size: 20
    each_class: 4
    num_workers: 0
    num_samples: 200
  format: txt
  modals: [image, label]
  types: [path, int]

global:
  gpu: null
  resume: null
  weight: null
  log_dir: ./runs/
  log_file: train.log
  num_epochs: 100
  save_epoch_steps: 1
  save_model_file: model-{}.pt
  save_checkpoint_file: last_checkpoint.txt
  report_interval: 4

model:
  TORCH_HOME: ../pretrained/
  name: resnet18
  pretrained: imagenet


loss:
  name: CosFaceLoss

optimizer:
  accum_steps: 1
  name: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0003

metric:
  name: metric_topk
  metric_topk: [1, 2, 4]

lr_strategy:
  name: stepwise
  start_lr: 0.01
  step_epochs: 2
  decay_scale: 0.1

