data:
  # mode: has 4 candidates:
  # [train, valid] or [train] or [valid] or [test]
  num_classes: 2
  mode: [test]
  # relative or absolute path to train, valid or test file
  train: null
  valid: null
  test: ../tests/test.txt
  output:
    # file to save
    file: null
    # topk or raw
    mode: top5
  # prefix path for each sample
  data_prefix: ../tests/
  # sampling strategy
  sampler:
    # class_balanced, null
    strategy: class_balanced
    batch_size: 10
    num_workers: 0
    num_samples: null
    replacement: true
  # json or txt
  format: txt
  # data modal: image, video, vector, text, label
  modals: [image, label]
  # data types:
  #  image: path, npy
  #  text: raw, token, file
  #  label: int
  types: [path, int] # e.g., image: path, npy, text: raw, token, file

global:
  gpu: null
  resume: ./runs/last_checkpoint.txt
  log_dir: ./runs/
  log_file: train.log
  num_epochs: 100
  save_epoch_steps: 5
  save_model_file: model-{}.pt
  save_checkpoint_file: last_checkpoint.txt
  report_interval: 4

model:
  # pretrained model should be placed into "pretrained" folder
  TORCH_HOME: ../pretrained/
  # network+classes+dataset (with pretraining), or network (w/o pretraining)
  name: resnet18
  # use default pretrained model: "imagenet"
  # or usre-defined model
  pretrained: null


loss:
  name: CrossEntropyLoss

optimizer:
  # steps to accumulate gradients: num > 0 or null
  accum_steps: 1
  # SGD, RMSprop
  name: SGD
  # null or 5
  clip_norm: null
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0003

metric:
  name: acc_topk
  acc_topk: [1]

lr_strategy:
  # stepwise, constant
  name: stepwise
  start_lr: 0.01
  step_epochs: 30
  decay_scale: 0.1

